### ISSUE TITLE
Session storage should not fallback to cookies

### ISSUE THREAD

**Issue by blowsie** [fredricrylander/angular-webstorage#16]
Session storage is, by design intended for potentially private data.
For this reason, it cannot be shared between tabs, or persist. And it is for this reason I think you should consider removing the cookie fallback for sessions storage. (or make it configurable)

---
Great work elsewhere by the way, great plugin!

**Comment by Toilal** [comment]
You should consider using [angular-locker](https://github.com/tymondesigns/angular-locker). It has a more consistent API, doesn't use cookie fallback, and is actively maintain.

**Comment by fredricrylander** [comment]
Added routines to check if local and/or session storage has been polyfilled or not. It is also possible to use the same routines to remove the polyfill functionality. `isPolyfilled(remove)` is now defined on `webStorage.local` and `webStorage.session`.
