### ISSUE TITLE
Naming of `add()`

### ISSUE THREAD

**Issue by blowsie** [fredricrylander/angular-webstorage#18]
If there a reason you opted for `add()` in the API? I personally think it should be `set()` and `get()`.
`add()` almost implies its just for adding , and not updating as well.

**Comment by timotheemoulin** [comment]
Hi, I also think that .set would be more appropriate as you can add several times the a value to the same property and the result is still the same (no duplication).

**Comment by fredricrylander** [comment]
I agree.
